#!/usr/bin/env bash

set -e -o pipefail

remote="mega"
list=(
    "$(xdg-user-dir DESKTOP)"
    "$(xdg-user-dir DOCUMENTS)"
    ~/notes
)

for x in "${list[@]}"
do
    if [[ -r "$x" ]]
    then    
        rclone sync "$@" "$x" "$remote:${x##*/}"
    else
        echo "$x doesn't exist; not backed up"
    fi
done
