#!/usr/bin/env python3
# Check for bad lines in files

import sys
import re

def cklns(f):
    a = []
    i = 1
    for line in f:
        if line[len(line) - 1] == '\n':
            line = line[:-1]
        if bad(line):
            a.append(i)
        i += 1
    return a

def ccols(line, ts):
    next = 0
    cols = 0
    for c in line:
        if cols >= next:
            next += ts
        if c == '\t':
            cols = next
        else:
            cols += 1
    return cols

def bad(line):
    b = False
    b = b or ccols(line, 8) > 80
    b = b or re.search('\s$', line)
    b = b or re.search(' \t', line)
    return b

if len(sys.argv) < 2:
    cklns(sys.stdin)
else:
    for s in sys.argv[1:]:
        with open(s) as f:
            a = cklns(f)
            if a:
                print(f'{s}:{a}')
