#!/bin/bash
# Lock the screen with pre and post hooks

e=xkb:us::eng
p=false
m=unmute

onlock () {
	e="$(ibus engine)"
	p="$(dunstctl is-paused)"
	m="$(amixer get Master | grep -q '\[on]' && echo unmute || echo mute)"

	ibus engine xkb:us::eng
	dunstctl set-paused true
	amixer set Master mute
}

onunlock () {
	ibus engine "$e"
	dunstctl set-paused "$p"
	amixer set Master "$m"
}

onlock
i3lock -n -i "$(find "$(xdg-user-dir DESKTOP)"/screensaver -mindepth 1 | randln)"
onunlock
