#!/usr/bin/env bash
# Print a random line from stdin or the file given by the first argument

set -e -o pipefail

if [[ -n "$1" ]] && [[ -r "$1" ]]
then
    exec 0< "$1"
fi

: '
if [[ -n "$1" ]] && [[ -r "$1" ]]
then
    exec randline <"$1"
fi
'

lines=()

while read -r
do
    lines+=("$REPLY")
done

echo "${lines[$RANDOM % ${#lines[@]}]}"
