#!/bin/bash
# Send keys to all tmux panes

set -e -o pipefail

[[ -n "$TMUX" ]] || exit 1

tmux lsp -F '#{pane_id} #{pane_pid}' | while read -r
do
	x=($REPLY)

	if [[ "$(ps --no-header -p "${x[1]}" -o cmd)" = "$SHELL" ]] && ! pgrep -P "${x[1]}" >/dev/null
	then
		tmux send-keys -t "${x[0]}" "$*" Enter
	fi
done
