#!/usr/bin/env bash

x="${1:-1}"
for i in $(xinput list | grep -i mouse | perl -n -e '/id=(\d+)/ && print "$1\n"')
do
	xinput --set-prop "$i" 'libinput Accel Profile Enabled' 0, 1
	xinput --set-prop "$i" 'libinput Accel Speed' 1
	xinput --set-prop "$i" 'Coordinate Transformation Matrix' "$x" 0 0 0 "$x" 0 0 0 1
done
