#!/usr/bin/env bash

x="${1:-1}"
for i in $(xinput list | grep -i mouse | perl -n -e '/id=(\d+)/ && print "$1\n"')
do
	xinput --set-prop "$i" 'libinput Accel Profile Enabled' 0, 1
	xinput --set-prop "$i" 'libinput Accel Speed' "$x"
done
