#!/usr/bin/env python
# Bare-bones SM-2 implementation

import argparse
import datetime
import os

class Card:
    def __init__(self, n, ef, i, pr, txt):
        self.n = n
        self.ef = ef
        self.i = i
        self.pr = pr
        self.txt = txt

    def default(txt):
        return Card(0, 2.5, 0, datetime.date.today(), txt)

    def __str__(self):
        return f'{self.n} {self.ef} {self.i} {self.pr} {self.txt}'

    def human_str(self):
        return f'{self.nr()} {self.txt}'

    def update(self, q):
        if q >= 3:
            if self.n == 0:
                self.i = 1
            elif self.n == 1:
                self.i = 6
            else:
                self.i = round(self.i * self.ef)
            self.n += 1
        else:
            self.n = 0
            self.i = 1

        self.ef = self.ef + (0.1 - (5 - q) * (0.08 + (5 - q) * 0.02))
        if self.ef < 1.3:
            self.ef = 1.3

        pr = datetime.date.today()

    def nr(self):
        return self.pr + datetime.timedelta(days=self.i)

    def is_due(self):
        return self.nr() - datetime.date.today() <= datetime.timedelta(days=0)

def read_card(line):
    line = line.split()
    n = int(line[0])
    ef = float(line[1])
    i = int(line[2])
    pr = datetime.date(*map(int, line[3].split('-')))
    txt = ' '.join(line[4:])
    return Card(n, ef, i, pr, txt)

def setup_cards_due():
    global cards_due
    cards_due = []
    for card in cards:
        if not card.is_due():
            break
        cards_due.append(card)

def sm2_add():
    cards.append(Card.default(args.txt))

def sm2_done():
    grade_map = {1: 0, 2: 3, 3: 4, 4: 5}
    setup_cards_due()
    if not args.card_num in range(0, len(cards_due)):
        print(f'error: card_num not in integer range [0, {len(cards_due) - 1}]')
    else:
        cards_due[args.card_num].update(grade_map[args.grade])

def sm2_list():
    if args.all:
        for card in cards:
            print(card.human_str())
    else:
        setup_cards_due()
        for i in range(0, len(cards_due)):
            print(f'[{i}] {cards[i].human_str()}')

# Argument parsing
parser = argparse.ArgumentParser()
parser.add_argument('--file', '-f', default=os.path.expanduser('~/.sm2'))
subparsers = parser.add_subparsers()

parser_list = subparsers.add_parser('list')
parser_list.add_argument('--all', '-a', action='store_true')
parser_list.set_defaults(func=sm2_list)

parser_add = subparsers.add_parser('add')
parser_add.add_argument('txt')
parser_add.set_defaults(func=sm2_add)

parser_done = subparsers.add_parser('done')
parser_done.add_argument('card_num', type=int)
parser_done.add_argument('grade', type=int, choices=range(1,5))
parser_done.set_defaults(func=sm2_done)

# Global variables
args = parser.parse_args()
cards = []

if not os.path.isfile(args.file):
    open(args.file, 'x')
with open(args.file, 'r') as file:
    for line in file:
        cards.append(read_card(line))

cards.sort(key=lambda card: card.nr())
args.func()

with open(args.file, 'w') as file:
    for card in cards:
        file.write(str(card) + '\n')
